name: Hexo Deploy
on:
  push:
    branches:
      - blog-source

jobs:
  build:
    runs-on: ubuntu-latest
    name: hexo deploy
    steps:
      - name: Cache node modules
        uses: actions/cache@v2
        id: cache
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: install hexo depencenies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          npm install hexo-cli -g
          npm install hexo-deployer-git --save
          npm install

      - name: generate page
        run: |
          hexo clean
          hexo generate

      - name: deploy
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          cp .deploy/config ~/.ssh/config
          eval $(ssh-agent)
          ssh-add ~/.ssh/id_rsa
          git config --global user.name "locez"
          git config --global user.email "loki.a@live.cn"
          hexo deploy
